export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California",
  "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
  "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
  "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
  "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
  "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
  "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
  "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
  "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
  "District of Columbia",
] as const;

// City-to-county mapping by state. This is a representative sample;
// the AI search will work with any city the user types in.
export const CITY_COUNTY_MAP: Record<string, Record<string, string>> = {
  Alabama: {
    Birmingham: "Jefferson County",
    Montgomery: "Montgomery County",
    Huntsville: "Madison County",
    Mobile: "Mobile County",
    Tuscaloosa: "Tuscaloosa County",
  },
  Alaska: {
    Anchorage: "Anchorage Borough",
    Fairbanks: "Fairbanks North Star Borough",
    Juneau: "Juneau Borough",
  },
  Arizona: {
    Phoenix: "Maricopa County",
    Tucson: "Pima County",
    Mesa: "Maricopa County",
    Scottsdale: "Maricopa County",
    Tempe: "Maricopa County",
    Flagstaff: "Coconino County",
  },
  Arkansas: {
    "Little Rock": "Pulaski County",
    "Fort Smith": "Sebastian County",
    Fayetteville: "Washington County",
  },
  California: {
    "Los Angeles": "Los Angeles County",
    "San Francisco": "San Francisco County",
    "San Diego": "San Diego County",
    "San Jose": "Santa Clara County",
    Sacramento: "Sacramento County",
    Oakland: "Alameda County",
    Fresno: "Fresno County",
    "Long Beach": "Los Angeles County",
    Bakersfield: "Kern County",
    Anaheim: "Orange County",
  },
  Colorado: {
    Denver: "Denver County",
    "Colorado Springs": "El Paso County",
    Aurora: "Arapahoe County",
    Boulder: "Boulder County",
    "Fort Collins": "Larimer County",
  },
  Connecticut: {
    Hartford: "Hartford County",
    "New Haven": "New Haven County",
    Bridgeport: "Fairfield County",
    Stamford: "Fairfield County",
  },
  Delaware: {
    Wilmington: "New Castle County",
    Dover: "Kent County",
    Newark: "New Castle County",
  },
  Florida: {
    Miami: "Miami-Dade County",
    Orlando: "Orange County",
    Tampa: "Hillsborough County",
    Jacksonville: "Duval County",
    "St. Petersburg": "Pinellas County",
    Tallahassee: "Leon County",
    "Fort Lauderdale": "Broward County",
  },
  Georgia: {
    Atlanta: "Fulton County",
    Savannah: "Chatham County",
    Augusta: "Richmond County",
    Columbus: "Muscogee County",
    Athens: "Clarke County",
  },
  Hawaii: {
    Honolulu: "Honolulu County",
    Hilo: "Hawaii County",
    Kailua: "Honolulu County",
  },
  Idaho: {
    Boise: "Ada County",
    Nampa: "Canyon County",
    "Idaho Falls": "Bonneville County",
  },
  Illinois: {
    Chicago: "Cook County",
    Springfield: "Sangamon County",
    Aurora: "Kane County",
    Rockford: "Winnebago County",
    Naperville: "DuPage County",
    Peoria: "Peoria County",
  },
  Indiana: {
    Indianapolis: "Marion County",
    "Fort Wayne": "Allen County",
    Evansville: "Vanderburgh County",
    "South Bend": "St. Joseph County",
  },
  Iowa: {
    "Des Moines": "Polk County",
    "Cedar Rapids": "Linn County",
    Davenport: "Scott County",
  },
  Kansas: {
    Wichita: "Sedgwick County",
    "Kansas City": "Wyandotte County",
    Topeka: "Shawnee County",
    "Overland Park": "Johnson County",
  },
  Kentucky: {
    Louisville: "Jefferson County",
    Lexington: "Fayette County",
    Frankfort: "Franklin County",
    "Bowling Green": "Warren County",
  },
  Louisiana: {
    "New Orleans": "Orleans Parish",
    "Baton Rouge": "East Baton Rouge Parish",
    Shreveport: "Caddo Parish",
    Lafayette: "Lafayette Parish",
  },
  Maine: {
    Portland: "Cumberland County",
    Augusta: "Kennebec County",
    Bangor: "Penobscot County",
  },
  Maryland: {
    Baltimore: "Baltimore City",
    Annapolis: "Anne Arundel County",
    Rockville: "Montgomery County",
    Frederick: "Frederick County",
    "Silver Spring": "Montgomery County",
  },
  Massachusetts: {
    Boston: "Suffolk County",
    Worcester: "Worcester County",
    Cambridge: "Middlesex County",
    Springfield: "Hampden County",
  },
  Michigan: {
    Detroit: "Wayne County",
    "Grand Rapids": "Kent County",
    "Ann Arbor": "Washtenaw County",
    Lansing: "Ingham County",
    Flint: "Genesee County",
  },
  Minnesota: {
    Minneapolis: "Hennepin County",
    "St. Paul": "Ramsey County",
    Rochester: "Olmsted County",
    Duluth: "St. Louis County",
  },
  Mississippi: {
    Jackson: "Hinds County",
    Gulfport: "Harrison County",
    Biloxi: "Harrison County",
  },
  Missouri: {
    "Kansas City": "Jackson County",
    "St. Louis": "St. Louis City",
    Springfield: "Greene County",
    Columbia: "Boone County",
    "Jefferson City": "Cole County",
  },
  Montana: {
    Billings: "Yellowstone County",
    Missoula: "Missoula County",
    Helena: "Lewis and Clark County",
  },
  Nebraska: {
    Omaha: "Douglas County",
    Lincoln: "Lancaster County",
  },
  Nevada: {
    "Las Vegas": "Clark County",
    Reno: "Washoe County",
    Henderson: "Clark County",
    "Carson City": "Carson City",
  },
  "New Hampshire": {
    Manchester: "Hillsborough County",
    Concord: "Merrimack County",
    Nashua: "Hillsborough County",
  },
  "New Jersey": {
    Newark: "Essex County",
    "Jersey City": "Hudson County",
    Trenton: "Mercer County",
    Paterson: "Passaic County",
    "Atlantic City": "Atlantic County",
  },
  "New Mexico": {
    Albuquerque: "Bernalillo County",
    "Santa Fe": "Santa Fe County",
    "Las Cruces": "Dona Ana County",
  },
  "New York": {
    "New York City": "New York County",
    Buffalo: "Erie County",
    Rochester: "Monroe County",
    Albany: "Albany County",
    Syracuse: "Onondaga County",
    Yonkers: "Westchester County",
  },
  "North Carolina": {
    Charlotte: "Mecklenburg County",
    Raleigh: "Wake County",
    Durham: "Durham County",
    Greensboro: "Guilford County",
    Asheville: "Buncombe County",
    "Winston-Salem": "Forsyth County",
  },
  "North Dakota": {
    Fargo: "Cass County",
    Bismarck: "Burleigh County",
    "Grand Forks": "Grand Forks County",
  },
  Ohio: {
    Columbus: "Franklin County",
    Cleveland: "Cuyahoga County",
    Cincinnati: "Hamilton County",
    Toledo: "Lucas County",
    Akron: "Summit County",
    Dayton: "Montgomery County",
  },
  Oklahoma: {
    "Oklahoma City": "Oklahoma County",
    Tulsa: "Tulsa County",
    Norman: "Cleveland County",
  },
  Oregon: {
    Portland: "Multnomah County",
    Salem: "Marion County",
    Eugene: "Lane County",
    Bend: "Deschutes County",
  },
  Pennsylvania: {
    Philadelphia: "Philadelphia County",
    Pittsburgh: "Allegheny County",
    Harrisburg: "Dauphin County",
    Allentown: "Lehigh County",
    Erie: "Erie County",
    Reading: "Berks County",
  },
  "Rhode Island": {
    Providence: "Providence County",
    Newport: "Newport County",
    Warwick: "Kent County",
  },
  "South Carolina": {
    Charleston: "Charleston County",
    Columbia: "Richland County",
    Greenville: "Greenville County",
    "Myrtle Beach": "Horry County",
  },
  "South Dakota": {
    "Sioux Falls": "Minnehaha County",
    "Rapid City": "Pennington County",
    Pierre: "Hughes County",
  },
  Tennessee: {
    Nashville: "Davidson County",
    Memphis: "Shelby County",
    Knoxville: "Knox County",
    Chattanooga: "Hamilton County",
  },
  Texas: {
    Houston: "Harris County",
    Dallas: "Dallas County",
    Austin: "Travis County",
    "San Antonio": "Bexar County",
    "Fort Worth": "Tarrant County",
    "El Paso": "El Paso County",
    "Corpus Christi": "Nueces County",
    Lubbock: "Lubbock County",
  },
  Utah: {
    "Salt Lake City": "Salt Lake County",
    Provo: "Utah County",
    "St. George": "Washington County",
    Ogden: "Weber County",
  },
  Vermont: {
    Burlington: "Chittenden County",
    Montpelier: "Washington County",
  },
  Virginia: {
    Richmond: "Richmond City",
    "Virginia Beach": "Virginia Beach City",
    Norfolk: "Norfolk City",
    Arlington: "Arlington County",
    Alexandria: "Alexandria City",
    Roanoke: "Roanoke City",
  },
  Washington: {
    Seattle: "King County",
    Tacoma: "Pierce County",
    Spokane: "Spokane County",
    Olympia: "Thurston County",
    Vancouver: "Clark County",
    Bellevue: "King County",
  },
  "West Virginia": {
    Charleston: "Kanawha County",
    Huntington: "Cabell County",
    Morgantown: "Monongalia County",
  },
  Wisconsin: {
    Milwaukee: "Milwaukee County",
    Madison: "Dane County",
    "Green Bay": "Brown County",
  },
  Wyoming: {
    Cheyenne: "Laramie County",
    Casper: "Natrona County",
    Jackson: "Teton County",
  },
  "District of Columbia": {
    Washington: "District of Columbia",
  },
};

export function getCitiesForState(state: string): string[] {
  return Object.keys(CITY_COUNTY_MAP[state] || {});
}

export function getCountyForCity(state: string, city: string): string {
  return CITY_COUNTY_MAP[state]?.[city] || "";
}
